### PR TITLE
Minor version bump

### PR DESCRIPTION
**Pull request by mforets**

### CODE REVIEW

**Comment by schillic** [comment]
I suggest to do the breaking change in #128 in the same version.

**Comment by mforets** [comment]
> I suggest to do the breaking change in #128 in the same version.

True, it would put 2 related changes on the same release, it's more organized than having them separated in 2 releases, I agree. On the other hand, that involves work that hasn't been done yet. In our development model, I'm on the camp of having small but frequent release cycles.

**Comment by schillic** [comment]
Okay, I'll do the change shortly.

**Comment by mforets** [comment]
Thanks!

**Pull request merged**
