### PR TITLE
Rename algebraic systems into descriptor systems

### PR DESCRIPTION
**Pull request by blegat**
I believe the correct terminology is "algebraic" to talk about the **equation** but "descriptor" to talk about the **system**.

### CODE REVIEW

**Review by schillic — APPROVED** [review]
I have no idea about the terminology, but I am fine with changing it. This would be a breaking change I guess.

**Comment by blegat** [comment]
Yes this is breaking unfortunately so that will need v0.13. We can wait a few days to see if there is any objection, there is no rush

**Review by mforets — APPROVED** [review]

**Comment by schillic** [comment]
@blegat Should we merge this and make a new release?

**Comment by blegat** [comment]
Yes, let's do it

**Pull request merged**
