### PR TITLE
Create @ivp macro

### PR DESCRIPTION
**Pull request by mforets**
Closes https://github.com/JuliaReach/MathematicalSystems.jl/issues/137

### CODE REVIEW

**Comment by mforets** [comment]
The idea is just to re-use the code for `@system` but return an error if `x(0) ... ` was not defined.

**Comment by ueliwechsler** [comment]
Can I push a proposal directly into this branch?

**Comment by mforets** [comment]
Yes, go ahead. When i get to the office i can review it. BTW yesterday i played around with `@ivp`, see the branch mforets/ivp_macro in this repo.

**Comment by ueliwechsler** [comment]
I like your version, would have done something similar. So no need to write my own proposal.
I just added a negative test for `@ivp` without specified `x(0)`.

One comment on your `mforets/ivp_macro`. I think you can throw the error like this 
` throw(ArgumentError("..."))` instead of  `:(throw("..."))`

**Comment by mforets** [comment]
> I like your version, would have done something similar. So no need to write my own proposal.

Ok, thanks for taking a look! I'll push it here then.

> I just added a negative test for @ivp without specified x(0).

Good idea, thanks.

> I think you can throw the error like this
throw(ArgumentError("...")) instead of :(throw("..."))

Alright, thanks for the tip.

**Comment by mforets** [comment]
This PR is read for review. Tests pass locally.

**Pull request merged**
