### PR TITLE
Add function to return vector_field of continuous system

### LINKED ISSUE #160: Add function to return gradient of continuous system
As mentioned in this post by @schillic in https://github.com/JuliaReach/MathematicalSystems.jl/issues/96#issuecomment-558502695
I suggest adding a functionality corresponding to the discrete `successor` method for continuous systems. Possible names are:
- `derivative`
- `tangent`
- `gradient`
- `vectorfield`

### PR DESCRIPTION
**Pull request by ueliwechsler**
Closes #160.

- Adds method `vector_field` to systems of type `AbstractContinuousSystem`.
- Rewrites `successor` method to make it more generic (no need to add a new method for every new type)
- add getter function `mapping` for retrieving the parametric function`:p` or blackbox function `:f`. (function name is WIP though)
- add `isblackbox` trait
- add Tests and docstring for `VectorField` type

### CODE REVIEW

**Comment by mforets** [comment]
Is this still WIP?

**Comment by ueliwechsler** [comment]
Sorry, I did not have that much time to work on this PR in the last weeks. 

The only thing that is left to do is the following:

> * add Tests and docstring for `VectorField` type
> * Export `VectorField` and `evaluate`? 

I am not really used to the wording of continuous systems and, to be honest, wording in general 😅. If you could provide some help, that would be really great.

But apart from adding documentation to the  `VectorField` part here 
https://github.com/JuliaReach/MathematicalSystems.jl/blob/74745b41d7b78deb2aaaf280c27edc26836b431b/src/instantiate.jl#L215-L237 and possibly adding a Test for `VectorField` this PR is fine. And should not be WIP.

**Comment by mforets** [comment]
Alright, thanks for the write-up. I'm enthusiastic about this PR as it gives access to `vector_field`. I'll think about naming suggestions and reply back.

**Comment by ueliwechsler** [comment]
Finally, I finished my work on  `vector_field`  and `successor` rewriting.

**Comment by schillic** [comment]
Can you split up the file `src/instantiate.jl`? At least I would not look for `successor` or `VectorField` in there. If there is something in common for all the content, a different name would be better.

**Comment by ueliwechsler** [comment]
Sure. I can create a file `vector_field.jl` and `successor.jl` for the corresponding code and keep the `_instantiate` "helper" methods in the `isntantiate.jl` file. I could move these three files into folder too. Any good namesuggestions?

**Comment by schillic** [comment]
Sounds good. I do not have suggestions for a folder name, but I also think we do not need a folder.

**Review by mforets — APPROVED** [review]
lgtm, thanks!

**Review by schillic — APPROVED** [review]
Thanks!
The `VectorField` struct is not tested I think.

**Comment by ueliwechsler** [comment]
I added the tests. Should be fine now.

**Comment by ueliwechsler** [comment]
I haven't done this in a while. Can I just merge or do I have to rebase or similar? 
I just remember, that the last time I tried, it ended for me in confusion and chaos😅.

**Comment by schillic** [comment]
Let's wait if @blegat has something to say. If you have the rights to do so, you can just merge (no conflict here).

**Comment by mforets** [comment]
Merging!

**Pull request merged**
